version: "3.8"
services:
  # front end
  frontapp:
    container_name: frontApp
    build: 
      context: ./frontApp
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - api
    depends_on:
      - serverapp
    links:
      - serverapp
    volumes:
      - ./users:/home/www/webapp
      - /home/www/webapp/node_modules
  # node server 
  serverapp:
    build: 
      context: ./serverApp
      dockerfile: ./Dockerfile
      args:
        DB_PORT: 27017
    restart: on-failure
    ports:
      - "3001:3001"
    networks:
      - api
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - ./publication:/home/www/webapp
      - /home/www/webapp/node_modules
  # elasticsearch
  elasticsearch:
    image:  elasticsearch:latest
    volumes:
      - dbdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: on-failure
    networks:
      - api
volumes:
  dbdata: {}
networks:
  api:
    driver: bridge
