version: "3.8"
services:
    # elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image:  elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    volumes:
      - dbdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: on-failure
    networks:
      - api
  # front end
  # frontapp:
  #   container_name: frontApp
  #   build: 
  #     context: ./frontApp
  #     dockerfile: ./Dockerfile
  #   restart: on-failure
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - api
  #   depends_on:
  #     - serverapp
  #   links:
  #     - serverapp
  #   volumes:
  #     - ./frontapp:/app
  #     - /app/node_modules
  # node server 
  serverapp:
    build: 
      context: ./serverApp
      dockerfile: ./Dockerfile
      args:
        DB: elasticsearch
    restart: on-failure
    environment: 
      WAIT_HOSTS: elasticsearch:9200
    ports:
      - "3001:3001"
    networks:
      - api
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - ./serverApp:/app
      - /app/node_modules
volumes:
  dbdata: {}
networks:
  api:
    driver: bridge
